use_frameworks!

platform :ios, '9.0'

source 'https://gitlab.oneitfarm.com/basemodule-ios/cibasemodulespec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'CIMiniProgram_Example' do
  pod 'CIMiniProgram', :path => '../'
  pod 'SGQRCode'
  pod 'Masonry'
  pod 'MBProgressHUD'
  pod 'SVProgressHUD'

  target 'CIMiniProgram_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
