use_frameworks!

platform :ios, '8.0'

target 'CIMiniProgram_Example' do
  pod 'CIMiniProgram', :path => '../'

  target 'CIMiniProgram_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
